# Generated by Django 4.1.1 on 2022-10-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aplication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citas",
            name="id_paciente",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="-", max_length=20, verbose_name="city"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="mail",
            field=models.CharField(default="-", max_length=45, verbose_name="email"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="-", max_length=20, verbose_name="phone"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Paciente",
        ),
    ]
